// import React from 'react';
// import { storiesOf } from '@storybook/react-native';

// import FilterList from './filterList';

// storiesOf('Filter', module).add('FilterList', () =>
// {
//     const data1 = [
//         {
//             'Id': 'f1161a51-d5b6-41b6-9717-16c105869a3c',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-09-23T03:37:58Z',
//             'Title': 'Đào Trọng Thắng',
//             'employee_guid': '614bf697f5532b43a1db9c45',
//             'employee_code': '1147',
//             'employee_full_name': 'Đào Trọng Thắng',
//             'employee_email': 'thangdt@fds.vn',
//             'employee_phone': '0919262988',
//             'employee_dob': '1984-12-31T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '12h - 16h',
//             'employee_username': 'thangdt',
//             'employee_vehicle_id': null,
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': '{"name":"E340C6E4-21D1-4A33-9863-BF4D39719E18.jpg","guid":"13bc8e1e-9431-402b-8a31-58bafc0e0467","mimetype":"image/jpeg"}',
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//             'employee_image_uri': 'https://dev.dcms.gisx.vn/api/ffms/containers/file-stream?fileId=13bc8e1e-9431-402b-8a31-58bafc0e0467&mimeType=image/jpeg',
//         },
//         {
//             'Id': 'bb98bb89-662c-48ea-ad41-68f33a9ffc28',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 36',
//             'employee_guid': '6167fbc7e2b5c8848e51641d',
//             'employee_code': null,
//             'employee_full_name': 'Worker 36',
//             'employee_email': 'dcms_worker36@vietbando.vn',
//             'employee_phone': '9586957836',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker36',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'e6f6ea8b-1fa3-4fdc-a236-e78a9a2382f1',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 47',
//             'employee_guid': '6167fc48e2b5c81bd251641f',
//             'employee_code': null,
//             'employee_full_name': 'Worker 47',
//             'employee_email': 'dcms_worker47@vietbando.vn',
//             'employee_phone': '9586957847',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker47',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '58e32bc4-e443-493b-afec-e5e043f205f6',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 49',
//             'employee_guid': '6167fc488b91a27a6b91ed4a',
//             'employee_code': null,
//             'employee_full_name': 'Worker 49',
//             'employee_email': 'dcms_worker49@vietbando.vn',
//             'employee_phone': '9586957849',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker49',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'c8242b40-7f35-4590-a44d-0e92b4154fea',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 50',
//             'employee_guid': '6167fc485fe39564b7bdf741',
//             'employee_code': null,
//             'employee_full_name': 'Worker 50',
//             'employee_email': 'dcms_worker50@vietbando.vn',
//             'employee_phone': '9586957850',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker50',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'f1370796-ab68-4cce-a61a-fab6b9389e6a',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 46',
//             'employee_guid': '6167fc485fe39527d2bdf740',
//             'employee_code': null,
//             'employee_full_name': 'Worker 46',
//             'employee_email': 'dcms_worker46@vietbando.vn',
//             'employee_phone': '9586957846',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker46',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'd2adce03-2a98-44cc-80a3-fd5ae108d4a7',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 42',
//             'employee_guid': '6167fc488b91a2bf8991ed49',
//             'employee_code': null,
//             'employee_full_name': 'Worker 42',
//             'employee_email': 'dcms_worker42@vietbando.vn',
//             'employee_phone': '9586957842',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker42',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '7521a601-4021-49b8-bd70-defc2cad2f3d',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 40',
//             'employee_guid': '6167fc485fe39585bfbdf742',
//             'employee_code': null,
//             'employee_full_name': 'Worker 40',
//             'employee_email': 'dcms_worker40@vietbando.vn',
//             'employee_phone': '9586957840',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker40',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'fd686d1c-d3e5-49ea-999f-fa34eb2c41ef',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 43',
//             'employee_guid': '6167fc485fe395e2cebdf73f',
//             'employee_code': null,
//             'employee_full_name': 'Worker 43',
//             'employee_email': 'dcms_worker43@vietbando.vn',
//             'employee_phone': '9586957843',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker43',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '9d6039ce-ddc1-494a-ad49-b7e19a4f7668',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 41',
//             'employee_guid': '6167fc48e2b5c8f791516420',
//             'employee_code': null,
//             'employee_full_name': 'Worker 41',
//             'employee_email': 'dcms_worker41@vietbando.vn',
//             'employee_phone': '9586957841',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker41',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '739f71d0-958a-4737-a115-548d5ffd6f57',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 45',
//             'employee_guid': '6167fc485fe39509eebdf743',
//             'employee_code': null,
//             'employee_full_name': 'Worker 45',
//             'employee_email': 'dcms_worker45@vietbando.vn',
//             'employee_phone': '9586957845',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker45',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'adaa08d8-8291-4266-abee-b145d284e1a4',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 44',
//             'employee_guid': '6167fc485fe39573c2bdf73e',
//             'employee_code': null,
//             'employee_full_name': 'Worker 44',
//             'employee_email': 'dcms_worker44@vietbando.vn',
//             'employee_phone': '9586957844',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker44',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '46990e63-874d-4019-a898-09dd20e112ce',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:45:44Z',
//             'Title': 'Worker 48',
//             'employee_guid': '6167fc48e2b5c8a10451641e',
//             'employee_code': null,
//             'employee_full_name': 'Worker 48',
//             'employee_email': 'dcms_worker48@vietbando.vn',
//             'employee_phone': '9586957848',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker48',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'e0f11276-3c62-4f88-b62a-4fd043eabaee',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 34',
//             'employee_guid': '6167fbc78b91a27aa591ed48',
//             'employee_code': null,
//             'employee_full_name': 'Worker 34',
//             'employee_email': 'dcms_worker34@vietbando.vn',
//             'employee_phone': '9586957834',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker34',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '8468fb3e-aa4b-48fe-a787-305c7b679f0d',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 33',
//             'employee_guid': '6167fbc75fe395aaf8bdf73d',
//             'employee_code': null,
//             'employee_full_name': 'Worker 33',
//             'employee_email': 'dcms_worker33@vietbando.vn',
//             'employee_phone': '9586957833',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker33',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '0b4b269e-6f0f-4f19-9160-96fde2caa166',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 38',
//             'employee_guid': '6167fbc78b91a2400791ed47',
//             'employee_code': null,
//             'employee_full_name': 'Worker 38',
//             'employee_email': 'dcms_worker38@vietbando.vn',
//             'employee_phone': '9586957838',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker38',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '211cafc8-08da-468c-b89f-14d30bc62cf5',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 39',
//             'employee_guid': '6167fbc78b91a2797c91ed46',
//             'employee_code': null,
//             'employee_full_name': 'Worker 39',
//             'employee_email': 'dcms_worker39@vietbando.vn',
//             'employee_phone': '9586957839',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker39',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'a4399651-56ff-4ff5-9bd2-dca932059df0',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 31',
//             'employee_guid': '6167fbc78b91a2794191ed45',
//             'employee_code': null,
//             'employee_full_name': 'Worker 31',
//             'employee_email': 'dcms_worker31@vietbando.vn',
//             'employee_phone': '9586957831',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker31',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '3a18c3d9-664c-489c-b6c7-b69d187f2852',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 32',
//             'employee_guid': '6167fbc7e2b5c841da51641c',
//             'employee_code': null,
//             'employee_full_name': 'Worker 32',
//             'employee_email': 'dcms_worker32@vietbando.vn',
//             'employee_phone': '9586957832',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker32',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'db42e234-c3cc-4552-8e42-46cb0ca79d00',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 37',
//             'employee_guid': '6167fbc78b91a2833091ed44',
//             'employee_code': null,
//             'employee_full_name': 'Worker 37',
//             'employee_email': 'dcms_worker37@vietbando.vn',
//             'employee_phone': '9586957837',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker37',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '24bc5ad9-16f4-4990-9f31-f9e42fcc3361',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 30',
//             'employee_guid': '6167fbc75fe3951416bdf73c',
//             'employee_code': null,
//             'employee_full_name': 'Worker 30',
//             'employee_email': 'dcms_worker30@vietbando.vn',
//             'employee_phone': '9586957830',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker30',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '0502d68c-1195-4ff0-b10a-3b1ac7a73737',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:35Z',
//             'Title': 'Worker 35',
//             'employee_guid': '6167fbc75fe395310cbdf73b',
//             'employee_code': null,
//             'employee_full_name': 'Worker 35',
//             'employee_email': 'dcms_worker35@vietbando.vn',
//             'employee_phone': '9586957835',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 3',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker35',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'a5467f25-bca8-4d56-b7af-c89f01d7c9ae',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 24',
//             'employee_guid': '6167fbb2e2b5c818f051641a',
//             'employee_code': null,
//             'employee_full_name': 'Worker 24',
//             'employee_email': 'dcms_worker24@vietbando.vn',
//             'employee_phone': '9586957824',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker24',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '032b0af6-dfb5-4bcb-a112-956e09f33d09',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 29',
//             'employee_guid': '6167fbb2e2b5c8eb0651641b',
//             'employee_code': null,
//             'employee_full_name': 'Worker 29',
//             'employee_email': 'dcms_worker29@vietbando.vn',
//             'employee_phone': '9586957829',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker29',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '73285c8e-48ed-4ed9-9467-f88b52814a20',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 27',
//             'employee_guid': '6167fbb25fe39549a9bdf73a',
//             'employee_code': null,
//             'employee_full_name': 'Worker 27',
//             'employee_email': 'dcms_worker27@vietbando.vn',
//             'employee_phone': '9586957827',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker27',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '07426eb9-29b3-45f0-9bc9-6f9c018a3165',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 28',
//             'employee_guid': '6167fbb25fe3953fb0bdf739',
//             'employee_code': null,
//             'employee_full_name': 'Worker 28',
//             'employee_email': 'dcms_worker28@vietbando.vn',
//             'employee_phone': '9586957828',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker28',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'b0c807fd-a65e-452e-b822-b2cfc8843176',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 25',
//             'employee_guid': '6167fbb2e2b5c88583516418',
//             'employee_code': null,
//             'employee_full_name': 'Worker 25',
//             'employee_email': 'dcms_worker25@vietbando.vn',
//             'employee_phone': '9586957825',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker25',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '98cda8e3-40b2-46cc-810b-bc8d15019525',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 21',
//             'employee_guid': '6167fbb25fe3959d58bdf738',
//             'employee_code': null,
//             'employee_full_name': 'Worker 21',
//             'employee_email': 'dcms_worker21@vietbando.vn',
//             'employee_phone': '9586957821',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker21',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'c85deda5-3c81-46ea-af0a-537788dd8f39',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 20',
//             'employee_guid': '6167fbb28b91a22c7a91ed43',
//             'employee_code': null,
//             'employee_full_name': 'Worker 20',
//             'employee_email': 'dcms_worker20@vietbando.vn',
//             'employee_phone': '9586957820',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker20',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '6e246171-8cb6-4f03-a9f6-6ad850725dcc',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 22',
//             'employee_guid': '6167fbb2e2b5c8a101516419',
//             'employee_code': null,
//             'employee_full_name': 'Worker 22',
//             'employee_email': 'dcms_worker22@vietbando.vn',
//             'employee_phone': '9586957822',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker22',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '7a3876f2-ad92-4b0c-adfe-03f14fc37237',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 26',
//             'employee_guid': '6167fbb28b91a24eb891ed42',
//             'employee_code': null,
//             'employee_full_name': 'Worker 26',
//             'employee_email': 'dcms_worker26@vietbando.vn',
//             'employee_phone': '9586957826',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker26',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '3e4304a6-e097-4a75-b690-a8eb9a373a40',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:43:14Z',
//             'Title': 'Worker 23',
//             'employee_guid': '6167fbb25fe3958bc5bdf737',
//             'employee_code': null,
//             'employee_full_name': 'Worker 23',
//             'employee_email': 'dcms_worker23@vietbando.vn',
//             'employee_phone': '9586957823',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker23',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Senior Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'e09aa33e-824e-4577-b4a7-2966ee397677',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 10',
//             'employee_guid': '6167fb908b91a2789e91ed3f',
//             'employee_code': null,
//             'employee_full_name': 'Worker 10',
//             'employee_email': 'dcms_worker10@vietbando.vn',
//             'employee_phone': '9586957810',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker10',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '1b43e454-c745-4005-b6d0-a4a2c58114a2',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 18',
//             'employee_guid': '6167fb908b91a2ec8d91ed3e',
//             'employee_code': null,
//             'employee_full_name': 'Worker 18',
//             'employee_email': 'dcms_worker18@vietbando.vn',
//             'employee_phone': '9586957818',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker18',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'a5e8550f-4220-4fc6-9779-0a78e79fae3f',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 14',
//             'employee_guid': '6167fb908b91a2a92091ed40',
//             'employee_code': null,
//             'employee_full_name': 'Worker 14',
//             'employee_email': 'dcms_worker14@vietbando.vn',
//             'employee_phone': '9586957814',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker14',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'b850b274-e0db-472d-bd0e-efafe7b55a62',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 15',
//             'employee_guid': '6167fb908b91a21e2491ed41',
//             'employee_code': null,
//             'employee_full_name': 'Worker 15',
//             'employee_email': 'dcms_worker15@vietbando.vn',
//             'employee_phone': '9586957815',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker15',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '9488f5fe-09c9-4a14-a38c-f1495fcea922',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 16',
//             'employee_guid': '6167fb908b91a23c2691ed3d',
//             'employee_code': null,
//             'employee_full_name': 'Worker 16',
//             'employee_email': 'dcms_worker16@vietbando.vn',
//             'employee_phone': '9586957816',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker16',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '1619d92b-0c32-4c33-bbe0-0f45bc199f9d',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 11',
//             'employee_guid': '6167fb90e2b5c88578516417',
//             'employee_code': null,
//             'employee_full_name': 'Worker 11',
//             'employee_email': 'dcms_worker11@vietbando.vn',
//             'employee_phone': '9586957811',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker11',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '6fe02604-3e83-440a-97dd-37d8ae1813c4',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 17',
//             'employee_guid': '6167fb905fe395aa26bdf736',
//             'employee_code': null,
//             'employee_full_name': 'Worker 17',
//             'employee_email': 'dcms_worker17@vietbando.vn',
//             'employee_phone': '9586957817',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker17',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '9f572918-4442-4760-b229-094bb05e3d04',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 19',
//             'employee_guid': '6167fb908b91a27c9d91ed3c',
//             'employee_code': null,
//             'employee_full_name': 'Worker 19',
//             'employee_email': 'dcms_worker19@vietbando.vn',
//             'employee_phone': '9586957819',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker19',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '883c3a07-974a-4da4-94d7-173ec62c204b',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 12',
//             'employee_guid': '6167fb905fe395db71bdf735',
//             'employee_code': null,
//             'employee_full_name': 'Worker 12',
//             'employee_email': 'dcms_worker12@vietbando.vn',
//             'employee_phone': '9586957812',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker12',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '658b2370-c6a6-4135-86a8-5b52f5e0dd51',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:40Z',
//             'Title': 'Worker 13',
//             'employee_guid': '6167fb90e2b5c8d578516416',
//             'employee_code': null,
//             'employee_full_name': 'Worker 13',
//             'employee_email': 'dcms_worker13@vietbando.vn',
//             'employee_phone': '9586957813',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 2',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker13',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Technician',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '22a721c4-89df-46fe-981b-accdfa2dbba8',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 3',
//             'employee_guid': '6167fb705fe3954634bdf734',
//             'employee_code': null,
//             'employee_full_name': 'Worker 3',
//             'employee_email': 'dcms_worker3@vietbando.vn',
//             'employee_phone': '9586957803',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker3',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'feabb96b-d6d8-4cf6-ae29-6b711bf0f05d',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 4',
//             'employee_guid': '6167fb70e2b5c84831516415',
//             'employee_code': null,
//             'employee_full_name': 'Worker 4',
//             'employee_email': 'dcms_worker4@vietbando.vn',
//             'employee_phone': '9586957804',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker4',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'e6e3fba6-72ae-4ac8-b460-5a3b0544856b',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 7',
//             'employee_guid': '6167fb70e2b5c85cfc516413',
//             'employee_code': null,
//             'employee_full_name': 'Worker 7',
//             'employee_email': 'dcms_worker7@vietbando.vn',
//             'employee_phone': '9586957807',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker7',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '1e5b69fe-64c9-427d-97bb-08cb708e0b8a',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 5',
//             'employee_guid': '6167fb70e2b5c840ec516414',
//             'employee_code': null,
//             'employee_full_name': 'Worker 5',
//             'employee_email': 'dcms_worker5@vietbando.vn',
//             'employee_phone': '9586957805',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker5',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '36cda638-7267-4d93-b66d-acf9b02bbd80',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 2',
//             'employee_guid': '6167fb705fe395dc3abdf733',
//             'employee_code': null,
//             'employee_full_name': 'Worker 2',
//             'employee_email': 'dcms_worker2@vietbando.vn',
//             'employee_phone': '9586957802',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker2',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '7f78d1cb-1d3d-4110-a08b-7525ceed00ef',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 9',
//             'employee_guid': '6167fb705fe3952d3dbdf732',
//             'employee_code': null,
//             'employee_full_name': 'Worker 9',
//             'employee_email': 'dcms_worker9@vietbando.vn',
//             'employee_phone': '9586957809',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker9',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '5eecb978-5b4d-466b-9e35-3018bc3abba6',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 8',
//             'employee_guid': '6167fb70e2b5c83c01516411',
//             'employee_code': null,
//             'employee_full_name': 'Worker 8',
//             'employee_email': 'dcms_worker8@vietbando.vn',
//             'employee_phone': '9586957808',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker8',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'ae17dbbb-b6bf-4646-9f79-70c9b56db3b3',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 1',
//             'employee_guid': '6167fb705fe3951413bdf731',
//             'employee_code': null,
//             'employee_full_name': 'Worker 1',
//             'employee_email': 'dcms_worker1@vietbando.vn',
//             'employee_phone': '9586957801',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker1',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '55e2f4ee-b45d-46d1-b1c8-6995449b3192',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-14T09:42:08Z',
//             'Title': 'Worker 6',
//             'employee_guid': '6167fb70e2b5c82e38516412',
//             'employee_code': null,
//             'employee_full_name': 'Worker 6',
//             'employee_email': 'dcms_worker6@vietbando.vn',
//             'employee_phone': '9586957806',
//             'employee_dob': '1990-01-03T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker6',
//             'employee_vehicle_id': 'Xe đạp',
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '73067f0c-1df7-4a6e-bc91-7d2cdf358aa3',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-09-27T07:47:40Z',
//             'Title': 'Lam Quang Cuong',
//             'employee_guid': '6151771df5532ba932db9c4a',
//             'employee_code': '1164',
//             'employee_full_name': 'Lam Quang Cuong',
//             'employee_email': 'cuonglq@vietbando.vn',
//             'employee_phone': '4859489384',
//             'employee_dob': '2021-09-25T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'mr.jelda',
//             'employee_vehicle_id': null,
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': '{"name":"rn_image_picker_lib_temp_351b93b5-d19a-415a-b183-2989c9b191f2.jpg","guid":"d78725e8-5da1-40e0-835d-54791cb2e429","mimetype":"image/jpeg"}',
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//             'employee_image_uri': 'https://dev.dcms.gisx.vn/api/ffms/containers/file-stream?fileId=d78725e8-5da1-40e0-835d-54791cb2e429&mimeType=image/jpeg',
//         },
//         {
//             'Id': '709b57b3-e9e7-4750-997b-4e461ab5aaf8',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-10-07T08:48:02Z',
//             'Title': 'Data Collector B',
//             'employee_guid': '615eb4426ad20a5ca8113a65',
//             'employee_code': null,
//             'employee_full_name': 'Data Collector B',
//             'employee_email': 'dcms_app@gmail.com',
//             'employee_phone': '123456789',
//             'employee_dob': '2021-09-26T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '8h - 12h',
//             'employee_username': null,
//             'employee_vehicle_id': null,
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'New',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': '01ebb5b5-3d6c-472d-84e8-12019075397e',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-08-27T08:17:51Z',
//             'Title': 'Data Collector Worker',
//             'employee_guid': '61289fae38ab1547e029778b',
//             'employee_code': '1046',
//             'employee_full_name': 'Data Collector Worker',
//             'employee_email': 'dcms_worker@vietbando.vn',
//             'employee_phone': '3475676843',
//             'employee_dob': null,
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_worker',
//             'employee_vehicle_id': null,
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': null,
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//         },
//         {
//             'Id': 'd15c2b15-d517-4e4d-924a-43f05500b5a6',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-09-23T11:13:33Z',
//             'Title': 'Vu Hoang Giang',
//             'employee_guid': '614c615ec3886b27ea6ed142',
//             'employee_code': '1150',
//             'employee_full_name': 'Vu Hoang Giang',
//             'employee_email': 'giangvh@fds.vn',
//             'employee_phone': '0705632412',
//             'employee_dob': '2021-09-07T17:00:00Z',
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'giangvh',
//             'employee_vehicle_id': null,
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': '{"name":"rn_image_picker_lib_temp_a1acc446-3665-4c66-b533-e5a947f9cb96.jpg","guid":"ad069030-d078-4874-8cc5-13c8ec64c211","mimetype":"image/jpeg"}',
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//             'employee_image_uri': 'https://dev.dcms.gisx.vn/api/ffms/containers/file-stream?fileId=ad069030-d078-4874-8cc5-13c8ec64c211&mimeType=image/jpeg',
//         },
//         {
//             'Id': '4f2d954d-afcf-4e88-a431-c873b1398f11',
//             'Layer': 'EMPLOYEE',
//             'CreatedDate': '2021-08-27T16:04:54Z',
//             'Title': 'Data Collector A',
//             'employee_guid': '61290d25d6041315042a98fa',
//             'employee_code': '1047',
//             'employee_full_name': 'Data Collector A',
//             'employee_email': 'dcms_workera@vietbando.vn',
//             'employee_phone': '4534543234',
//             'employee_dob': null,
//             'employee_team_id': 'Team 1',
//             'employee_shift_id': '16h - 20h',
//             'employee_username': 'dcms_workera',
//             'employee_vehicle_id': null,
//             'employee_organization_id': 'ABC Electronics',
//             'employee_type_id': 'Driver',
//             'employee_status': 'Active',
//             'employee_image': '{"name":"rn_image_picker_lib_temp_9d67a036-c191-4052-aa26-7003d6a81d46.jpg","guid":"11de4731-05a1-4364-ab14-b5c788dc92ee","mimetype":"image/jpeg"}',
//             'employee_number': 0,
//             'employee_date': null,
//             'employee_list': null,
//             'employee_image_uri': 'https://dev.dcms.gisx.vn/api/ffms/containers/file-stream?fileId=11de4731-05a1-4364-ab14-b5c788dc92ee&mimeType=image/jpeg',
//         },
//     ];
//     const dataName = data1.map((item)=>
//     {
//         return item.employee_full_name;
//     });
//     const dataOnpress = data1.map((item)=>
//     {
//         return item.employee_username;
//     });
//     let checkJobEmployee = [];
//     data1.map(()=>
//     {
//         checkJobEmployee.push(false);
//     });
//     const handleCheckEmployee = (index:number) =>
//     {
//         const tmpListCheckEmployee: boolean[] = [];
//         data1.map((x,index2) =>
//         {
//             if (index2 === index)
//             {
//                 tmpListCheckEmployee.push(!checkJobEmployee[index]);
//             }
//             else if (checkJobEmployee[index2] === false)
//             {
//                 tmpListCheckEmployee.push(checkJobEmployee[index2]);
//             }
//             else
//             {
//                 tmpListCheckEmployee.push(true);
//             }
//         });
//         checkJobEmployee = (tmpListCheckEmployee);
//         console.log(tmpListCheckEmployee);
//         // console.log('jobList check',checkTypeList);
//     };
//     return (
//         <FilterList
//             title="Employee"
//             dataName={dataName}
//             // dataOnpress={dataOnpress}
//             check={checkJobEmployee}
//             onPress={(x)=>handleCheckEmployee(x)}
//         />
//     );
// });
