// import React, { useEffect, useState } from 'react';
// import { storiesOf } from '@storybook/react-native';

// import { View } from 'react-native';
// import { TreeSelect } from './TreeSelect';

// const json = [
//     {
//         'Id': 'b16f400a-9307-47f3-b8b8-2f81b003e336',
//         'Layer': 'CONTAINER',
//         'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//         'Type': 'folder',
//         'CreatedUserId': 2,
//         'ModifiedUserId': 2,
//         'CreatedDate': '2018-11-07T08:53:02Z',
//         'ModifiedDate': '2018-11-07T08:53:02Z',
//         'Name': 'Buuchinhvienthong',
//         'label': 'Bưu chính viễn thông',
//         'Description': null,
//         'Content': null,
//         'Extension': null,
//         'FileId': null,
//         'isLoaded': true,
//         'child': [
//             {
//                 'Id': 'caf6f511-bf8d-4e3d-86fd-7c097076eeb0',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'Type': 'folder',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T06:59:43Z',
//                 'ModifiedDate': '2018-11-30T06:59:43Z',
//                 'Name': '5c24420e-cae9-4443-a043-98ccb3f5887d',
//                 'label': 'Internet',
//                 'Description': null,
//                 'Extension': null,
//                 'FileId': null,
//                 'isLoaded': true,
//                 'child': [
//                     {
//                         'Id': 'b8bf0b96-33d7-410b-99df-5ca72f0ad',
//                         'Layer': 'CONTAINER',
//                         'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/1dd78ad7-7fcf-4de2-a1d0-9dcb61cf6ed8',
//                         'Type': 'maplayer',
//                         'CreatedUserId': 2,
//                         'ModifiedUserId': 2,
//                         'CreatedDate': '2018-11-30T07:00:00Z',
//                         'ModifiedDate': '2018-11-30T07:00:00Z',
//                         'Name': '1dd78ad7-7fcf-4de2-a1d0-9dcb61cf6ed8',
//                         'label': 'Bưu cục',
//                         'Description': null,
//                         'Content': '{"Caption":"B\\u01b0u c\\u1ee5c","LayerName":"PST_POSTOFFICE","Order":0,"LayerType":"OVERLAY"}',
//                         'Extension': null,
//                         'FileId': null,
//                         'layerInfo': {
//                             'Caption': 'Bưu cục',
//                             'LayerName': 'PST_POSTOFFICE',
//                             'Order': 0,
//                             'LayerType': 'OVERLAY',
//                         },
//                         'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                         'checkingType': 0,
//                         'isLoaded': false,
//                         'child': [],
//                     },
//                 ],
//             },
//             {
//                 'Id': 'b8bf0b96-33d7-410b-99df-5ca72f0ad3b5',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/1dd78ad7-7fcf-4de2-a1d0-9dcb61cf6ed8',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:00:00Z',
//                 'ModifiedDate': '2018-11-30T07:00:00Z',
//                 'Name': '1dd78ad7-7fcf-4de2-a1d0-9dcb61cf6ed8',
//                 'label': 'Bưu cục',
//                 'Description': null,
//                 'Content': '{"Caption":"B\\u01b0u c\\u1ee5c","LayerName":"PST_POSTOFFICE","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Bưu cục',
//                     'LayerName': 'PST_POSTOFFICE',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': '3705b911-c390-48a1-a75f-93cfcd16ee47',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/849f7e50-bcaa-481b-b378-67292c2e3d71',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:00:13Z',
//                 'ModifiedDate': '2018-11-30T07:00:13Z',
//                 'Name': '849f7e50-bcaa-481b-b378-67292c2e3d71',
//                 'label': 'Doanh nghiệp bưu chính',
//                 'Description': null,
//                 'Content': '{"Caption":"Doanh nghi\\u1ec7p b\\u01b0u ch\\u00ednh","LayerName":"PST_POSTAL","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Doanh nghiệp bưu chính',
//                     'LayerName': 'PST_POSTAL',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': '61c48233-51cb-4e72-b941-be43eb50a23b',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/81a25879-93f2-4885-a987-af1c051f3258',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:00:39Z',
//                 'ModifiedDate': '2018-11-30T07:00:39Z',
//                 'Name': '81a25879-93f2-4885-a987-af1c051f3258',
//                 'label': 'Phát thanh truyền hình tương tự',
//                 'Description': null,
//                 'Content': '{"Caption":"Ph\\u00e1t thanh truy\\u1ec1n h\\u00ecnh t\\u01b0\\u01a1ng t\\u1ef1","LayerName":"FRQ_TRUYENHINHTUONGTU","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Phát thanh truyền hình tương tự',
//                     'LayerName': 'FRQ_TRUYENHINHTUONGTU',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': 'fb022809-542b-422f-a008-fe9404649e53',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/665ebb2d-4fd9-439f-a986-c5b00f026907',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:01:28Z',
//                 'ModifiedDate': '2018-11-30T07:01:28Z',
//                 'Name': '665ebb2d-4fd9-439f-a986-c5b00f026907',
//                 'label': 'Quản lý tuyến cáp',
//                 'Description': null,
//                 'Content': '{"Caption":"Qu\\u1ea3n l\\u00fd tuy\\u1ebfn c\\u00e1p","LayerName":"NET_CABLE","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Quản lý tuyến cáp',
//                     'LayerName': 'NET_CABLE',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': '611db8e5-a2be-4ce1-b22d-d6d9842567c4',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/d9fa171c-fe45-41fb-9353-8c5c9ffc629d',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:01:41Z',
//                 'ModifiedDate': '2018-11-30T07:01:41Z',
//                 'Name': 'd9fa171c-fe45-41fb-9353-8c5c9ffc629d',
//                 'label': 'Giấy phép BTS',
//                 'Description': null,
//                 'Content': '{"Caption":"Gi\\u1ea5y ph\\u00e9p BTS","LayerName":"BTS_STATION","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Giấy phép BTS',
//                     'LayerName': 'BTS_STATION',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': 'acedc74b-c891-4544-9d3a-cd3bc28e37b2',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/adcae6a5-57df-4693-8d95-5f6c4b997d14',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:01:51Z',
//                 'ModifiedDate': '2018-11-30T07:01:51Z',
//                 'Name': 'adcae6a5-57df-4693-8d95-5f6c4b997d14',
//                 'label': 'Đại lý Game',
//                 'Description': null,
//                 'Content': '{"Caption":"\\u0110\\u1ea1i l\\u00fd Game","LayerName":"INT_GAMEONLINE","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Đại lý Game',
//                     'LayerName': 'INT_GAMEONLINE',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': 'a00e03df-95f9-4e00-9cde-a52583381bf6',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/bbd6c1a4-7ce9-489e-b1d6-148f4a4ea549',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:02:03Z',
//                 'ModifiedDate': '2018-11-30T07:02:03Z',
//                 'Name': 'bbd6c1a4-7ce9-489e-b1d6-148f4a4ea549',
//                 'label': 'Hạ tầng ngầm',
//                 'Description': null,
//                 'Content': '{"Caption":"H\\u1ea1 t\\u1ea7ng ng\\u1ea7m","LayerName":"NET_MAIN_CABLE","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Hạ tầng ngầm',
//                     'LayerName': 'NET_MAIN_CABLE',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': '09a3733d-e4c7-48c3-a346-74e3487006a4',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/f8e0a84e-aa3f-444e-8df9-7eabf2b617ca',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:02:15Z',
//                 'ModifiedDate': '2018-11-30T07:02:15Z',
//                 'Name': 'f8e0a84e-aa3f-444e-8df9-7eabf2b617ca',
//                 'label': 'Phát thanh truyền hình số',
//                 'Description': null,
//                 'Content': '{"Caption":"Ph\\u00e1t thanh truy\\u1ec1n h\\u00ecnh s\\u1ed1","LayerName":"FRQ_TRUYENHINHSO","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Phát thanh truyền hình số',
//                     'LayerName': 'FRQ_TRUYENHINHSO',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': 'ef425e16-5dc6-47ed-8f37-1b87c3a8e9a5',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/96354ebc-54d1-44fc-8fd7-b68b005ed9ab',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:02:27Z',
//                 'ModifiedDate': '2018-11-30T07:02:27Z',
//                 'Name': '96354ebc-54d1-44fc-8fd7-b68b005ed9ab',
//                 'label': 'Quản lý trụ, trạm',
//                 'Description': null,
//                 'Content': '{"Caption":"Qu\\u1ea3n l\\u00fd tr\\u1ee5, tr\\u1ea1m","LayerName":"NET_POST","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Quản lý trụ, trạm',
//                     'LayerName': 'NET_POST',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': 'b8c347bf-b28d-4a93-aa00-1eec00e4e52a',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/7192c680-885f-4aa0-84b4-969383552d15',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:02:38Z',
//                 'ModifiedDate': '2018-11-30T07:02:38Z',
//                 'Name': '7192c680-885f-4aa0-84b4-969383552d15',
//                 'label': 'Lưu động, dùng riêng',
//                 'Description': null,
//                 'Content': '{"Caption":"L\\u01b0u \\u0111\\u1ed9ng, d\\u00f9ng ri\\u00eang","LayerName":"FRQ_LICENCE","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Lưu động, dùng riêng',
//                     'LayerName': 'FRQ_LICENCE',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': '710c2b31-540e-4427-9884-944d509e51e5',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/2c161a51-b117-4230-88c8-d5ff48ff6650',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:02:53Z',
//                 'ModifiedDate': '2018-11-30T07:02:53Z',
//                 'Name': '2c161a51-b117-4230-88c8-d5ff48ff6650',
//                 'label': 'Quản lý điểm cung cấp dịch vụ viễn thông',
//                 'Description': null,
//                 'Content': '{"Caption":"Qu\\u1ea3n l\\u00fd \\u0111i\\u1ec3m cung c\\u1ea5p d\\u1ecbch v\\u1ee5 vi\\u1ec5n th\\u00f4ng","LayerName":"SIM_TELECOMSERVICE","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Quản lý điểm cung cấp dịch vụ viễn thông',
//                     'LayerName': 'SIM_TELECOMSERVICE',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': 'c3d1d40f-2eac-4695-92a4-4ed9950e49f1',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/fa3b30e9-b19c-42a0-987f-eeb2a2cc9022',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:03:08Z',
//                 'ModifiedDate': '2018-11-30T07:03:08Z',
//                 'Name': 'fa3b30e9-b19c-42a0-987f-eeb2a2cc9022',
//                 'label': 'Truyền thanh không dây',
//                 'Description': null,
//                 'Content': '{"Caption":"Truy\\u1ec1n thanh kh\\u00f4ng d\\u00e2y","LayerName":"FRQ_TRUYENTHANHKHONGDAY","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Truyền thanh không dây',
//                     'LayerName': 'FRQ_TRUYENTHANHKHONGDAY',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': '7cdbcb81-60c2-4177-a670-b7aedb68c2f1',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/b4e25ff7-34b4-4945-adc6-9978b5139ad0',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:03:25Z',
//                 'ModifiedDate': '2018-11-30T07:03:25Z',
//                 'Name': 'b4e25ff7-34b4-4945-adc6-9978b5139ad0',
//                 'label': 'Quản lý dữ liệu điểm phân phối sim',
//                 'Description': null,
//                 'Content': '{"Caption":"Qu\\u1ea3n l\\u00fd d\\u1eef li\\u1ec7u \\u0111i\\u1ec3m ph\\u00e2n ph\\u1ed1i sim","LayerName":"SIM_SIMREGISTRATION","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Quản lý dữ liệu điểm phân phối sim',
//                     'LayerName': 'SIM_SIMREGISTRATION',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//             {
//                 'Id': 'd0a298ed-bc47-406f-bf85-2eb0f3cec7e2',
//                 'Layer': 'CONTAINER',
//                 'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/ab276252-dfd9-4da5-a52e-bcbd7e4fe26b',
//                 'Type': 'maplayer',
//                 'CreatedUserId': 2,
//                 'ModifiedUserId': 2,
//                 'CreatedDate': '2018-11-30T07:03:31Z',
//                 'ModifiedDate': '2018-11-30T07:03:31Z',
//                 'Name': 'ab276252-dfd9-4da5-a52e-bcbd7e4fe26b',
//                 'label': 'Tòa nhà',
//                 'Description': null,
//                 'Content': '{"Caption":"T\\u00f2a nh\\u00e0","LayerName":"TOA_NHA","Order":0,"LayerType":"OVERLAY"}',
//                 'Extension': null,
//                 'FileId': null,
//                 'layerInfo': {
//                     'Caption': 'Tòa nhà',
//                     'LayerName': 'TOA_NHA',
//                     'Order': 0,
//                     'LayerType': 'OVERLAY',
//                 },
//                 'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//                 'checkingType': 0,
//                 'isLoaded': false,
//                 'child': [],
//             },
//         ],
//     },
// ];


// json.push({
//     'Id': 'd0a298ed-bc47-406f-bf85-2eb0f3cec7e21',
//     'Layer': 'CONTAINER',
//     'Path': '/root/vdms/hethong/maplayer/default/buuchinhvienthong/ab276252-dfd9-4da5-a52e-bcbd7e4fe26b',
//     'Type': 'maplayer',
//     'CreatedUserId': 2,
//     'ModifiedUserId': 2,
//     'CreatedDate': '2018-11-30T07:03:31Z',
//     'ModifiedDate': '2018-11-30T07:03:31Z',
//     'Name': 'ab276252-dfd9-4da5-a52e-bcbd7e4fe26b',
//     'label': 'Tòa nhà',
//     'Description': null,
//     'Content': '{"Caption":"T\\u00f2a nh\\u00e0","LayerName":"TOA_NHA","Order":0,"LayerType":"OVERLAY"}',
//     'Extension': null,
//     'FileId': null,
//     'layerInfo': {
//         'Caption': 'Tòa nhà',
//         'LayerName': 'TOA_NHA',
//         'Order': 0,
//         'LayerType': 'OVERLAY',
//     },
//     'ParentPath': '/root/vdms/hethong/maplayer/default/buuchinhvienthong',
//     'checkingType': 0,
//     'isLoaded': false,
//     'child': [],
// });


// const App = () =>
// {
//     const [data,setData] = useState<any>();
//     const [finaa,setFinal] = useState<any>();

//     useEffect(() =>
//     {
//         const final = data?.filter(e=> e.layerInfo !== undefined).map(e=>
//         {
//             return { ...e.layerInfo,Id: e.Id };
//         });
//         setFinal(final);
//     },[data]);
//     console.log(finaa);
//     return (
//         <View>
//             <TreeSelect
//                 data={json}
//                 hasSearch={false}
//                 height={'100%'}
//                 showTag
//                 onChecked={setData}
//             />

//         </View>
//     );
// };
// storiesOf('Layout', module).add('TreeSelect', () => (
//     <App />
// ));
